---
title: "Salzburg City Population Analysis"
output: 
  flexdashboard::flex_dashboard:
    source_code: "https://github.com/csaybar/digitalearth/tree/master/assigments/carto_proj/assigment_02"
    storyboard: no
    social: menu
    source: embed
    css: style/style.css
---

```{r}
knitr::opts_chunk$set(echo = FALSE)
```


```{r setup, include=FALSE}
library(tidyverse)
library(htmltools)
library(leaflet)
library(mapview)
library(scales)
library(plotly)
library(trend)
library(sf)
source("scripts/functions.R")
states <- read_sf("data/salzburg_population.geojson")
```
    
Column {data-width=185}
-------------------------------------

Salzburg is the capital city of the State of Salzburg and fourth-largest city in Austria. In 2020, it had a population of **156,872**. Using the WorldPop Global Project Population Data ([WorldPop](https://www.worldpop.org/)) we analysis population changes from 2000-2019.

**`Salzburg population density map`**

From the 33 Salzburg districts we observed that 10 of them present a population density greater than  **3000** **people/ km<sup>2</sup>** (red ones). These are: Neustadt, Lehen-Nord, Elisabeth-Vorstadt, Liefering-Ost, Taxham, Schallmoos, Maxglan, Liefering-West, Aiglhof/Innere Riedenburg, and Rechte Altstadt/Andräviertel. 

On the other hand, Hellbrunn and Gaisberg were the district with the lowest population density (yellow one) presenting a value of 863 and 430 **people/ km<sup>2</sup>** respectively. 

**`Salzburg population trends map`**

In the city of Salzburg we observed that 31 districts present a positive tau and a pvalue lower than 0.01. The **Parsch Ost/Aigen** and **Aigen/Glas** districts showed the highest population growth rate.

**`Salzburg population statistics`**

Display the **standard score** values can give us a better idea of the growth rates of each district.

Column {.tabset}
-------------------------------------
   
### Salzburg density map

```{r}
# 2. Create map
map_base(states)
```   

### Salzburg population trends

```{r}
# 3. Create trend and density columns -------------------------------------
states$tau <- map_create_trends(states, estimator = "tau")
states$slope <- map_create_trends(states, estimator = "slope")
```


```{r}
# 2. Create map
map_tau(states)
```   

### Salzburg population statistics

```{r include, echo = FALSE}
pp <- map_plotly_graph(states)
htmlwidgets::saveWidget(pp, "plot.html")
htmltools::tags$iframe(
  src=file.path(getwd(), "plot.html"),
  width="100%",
  height="100%",
  scrolling="no",
  seamless="seamless",
  frameBorder="0"
)
```